version: 2
jobs:
  build:
    main.cpp
    docker:
      -image: debian:stretch
     steps:
      -checkout
      -run:
        name: Greeting
        command: echo Hello, Word.
       -run:
        name: Print the Current Time
        command: date
