version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run: sudo apt-get install gcc
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  
